### ISSUE TITLE
Doesn't compile with D 2.067

### ISSUE THREAD

**Issue by maaaks** [robik/DIni#13]
I have just upgraded `dmd` from 2.066.1 to 2.067.0 on my Ubuntu 14.10, and my project which uses DIni stopped compiling because of this line in `dini.d`:
```d
import std.array  : split, indexOf, replaceInPlace, join;
```

The `indexOf()` function seems to be moved into `std.string`. However, as far as I can see, you don't really use `indexOf`in the code, so you can just remove import of `indexOf` from the line. If you do so, the library successfully compiles.

P.S. If you will update version of package when fixing it, tell me, and I will update http://code.dlang.org/packages/dini.

**Comment by JesseKPhillips** [comment]
This has pull request #7 that fixes this issue.

**Comment by robik** [comment]
PR merged.
