### ISSUE TITLE
module std.array import 'indexOf' not found

### ISSUE THREAD

**Issue by maaaks** [robik/DIni#14]
DIni tries to import unexistent symbol `indexOf`:

> ../../home/maaaks/.dub/packages/dini-1.0.0/src/dini.d(12): Error: module std.array import 'indexOf' not found, did you mean 'alias IndexOf'?

However, if I remove the `indexOf` from that line, everything compiles successfully. I think you should remove it from source (and maybe check for other old unused imports).

**Comment by JesseKPhillips** [comment]
@robik, can you tag Master with v1.0.1 so that dub can pull this fix down?
