### ISSUE TITLE
Saving ini files help

### ISSUE THREAD

**Issue by joelcnz** [robik/DIni#18]
http://www.dprogramming.com/ini.php has ini library that has save in it. Maybe you could look at his code.

There might be a bug in his code, I can send you my version if you want.

His code uses std.stream (deprecated), so that's why I don't want to use it.

O, looks like you've seen the file. And my version has no tabs and spaces a the start of each line.

Allegro has an ini setup.

The save without comments would be better than no save at all, I think.

**Comment by JesseKPhillips** [comment]
You can check out my updates to the dprogramming ini.d file: https://github.com/JesseKPhillips/ini.d/tree/D2

**Comment by robik** [comment]
Sorry for late reply, haven't logged in for a whilte. Saving INI files (among other things) is being worked on in new major version of dini. Can't say when it will be released but probably later next month.

**Comment by joelcnz** [comment]
I've made my own version of saving ini file, but it is horribly slow.

Yes, that what I wanted. Thanks JesseKPhillips.
