### ISSUE TITLE
error parsing config

### ISSUE THREAD

**Issue by bubnenkoff** [robik/DIni#4]
My case is not standard. I am storing in config part of POST request, but I really not found nothing better.
dini fail on next config:

```key1 = NW_Pacific%2FOverview%2Fvis_ir_background%2Fgms_6_lowcloud&DIR=%2Fnexsat_data%2FPUBLIC%2FCONUS%2Ffocus_regions%2FNW_Pacific%2FOverview%2Fvis_ir_background=```

**Comment by robik** [comment]
You can pass `Ini.Parse[String](target, false)` to disable lookups.
